#page title
page_title                                : Quellenreiter:in - Das "Fake News" Quiz                      # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                           # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           :                                           # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/logo-pink.png                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Quellenreiter:in                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Wir helfen spielerisch "Fake News" zu erkennen.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Jannik und Simon                              
your_link                                 :                     
your_city                                 : Berlin                                
email_address                             : quellenreiter.app@gmail.com
facebook_username                         :                                           
instagram_username                        : quellenreiter.app
twitter_username                          : QuellenReiterDE
github_username                           : QuellenReiter
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Bewerte “Real News” und “Fake News” anhand von Quellen und Faktenchecks
    description                           : So lernst Du "Fake News"zu entlarven und erhältst einen Überblick über die deutsche Medienlandschaft.
    fontawesome_icon_name                 : gamepad
    
  - title                                 : Spiele im Multiplayer gegen deine Freund:innen
    description                           : Wie Fortnite, nur ganz anders
    fontawesome_icon_name                 : users

  - title                                 : Standardisierte, frei zugängliche Desinformations-Datenbank
    description                           : Die “Fake News”-Datenbank wird für alle Internetnutzer:innen zugänglich sein, und verifizierte Faktencheck-Redaktionen haben die Möglichkeit, die Datenbank zu erweitern.
    fontawesome_icon_name                 : book-open

  - title                                 : Im Austausch mit Lehrkräften und Medienkompetenz-Organisationen
    description                           : Die App funktioniert nicht nur als Quiz, sondern auch als Lernplattform, welche die Medienkompetenzvermittlung an Schulen erleichtert.
    fontawesome_icon_name                 : user-graduate

  - title                                 : Open Source, kostenlos und ohne Werbung
    description                           : So kann das Projekt frei zugänglich Nachrichtenkompetenzen in der Zivilgesellschaft fördern.
    fontawesome_icon_name                 : rocket
  
  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

# People List                            Edit, add or remove features to be presented.
people                                    :

  - title                                 : Jannik Werner
    text                                  : Redatktion | Faktencheck | Entwicklung
    avatar                                : assets/jannik.jpg
    
  - title                                 : Simon Sasse
    text                                  : Programmierung | Design | Entwicklung
    avatar                                : assets/simon.jpg

# Sponsors List                            Edit, add or remove features to be presented.
logos                                     :

  - url                                   : assets/bmbf.jpg
    
  - url                                   : assets/okfd.svg

  - url                                   : assets/pf.png

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : yellow                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"
header_background_color                   : "#0999bc"
link_color                                : "#ff3a93"
header_text_color                         : "#c7ebeb"

app_title_color                           : "#c7ebeb"
app_price_color                           : "#c7ebeb"
app_description_color                     : "#c7ebeb"

feature_title_color                       : "#666666"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#f5df5b"
feature_icons_background_color            : "#ff3a93"

social_icons_foreground_color             : "#f5df5b"
social_icons_background_color             : "#0999bc"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
